#APPLICATION BROWSER
browser=crome
#APPLICATION URL
url = https://www.demoblaze.com/
#APPLICATION CREDENTIALS
username =test.danny
password = danny123

name = Paul Daniel
country = India
city = Chennai
card = 1111 2222 3333 4444
month = Sep
year = 2026